### ISSUE TITLE
feat: self-subscribing universal middlewares

### ISSUE THREAD

**Issue by brillout** [magne4000/universal-middleware#22]
> Server framework extensions:
> - vike-express
> - vike-hono
> - vike-fastify
> - ...
> 
> These would automatically integrate universal middlewares (by creating a new setting `+middleware`). For example, adding Telefunc to an existing app will be done simply by adding `vike-telefunc`: the Telefunc middleware is then automatically added

How could Telefunc's universal middleware define its URL route? Maybe we'll need https://github.com/magne4000/universal-middleware/discussions/4 at some point :thinking:

**Comment by magne4000** [comment]
I was going to say that it should not declare its route, to keep things simple.
A package using `universal-middleware` could also export its "suggested" route like this:

```ts
import telefuncHandler from "telefunc/middleware/hono";
import telefuncRoute from "telefunc/middleware/hono-route";

...
app.post(telefuncRoute, telefuncHandler());
```

But this route will:
1. not necessarily be compatible with all servers. For instance, the fail-over handler route in Hono is `"*"`, but in h3 is `"/**"`
2. not be tied to what the user could have possibly overridden through the handler configuration

Let me explain this second point:

```ts
const handler = telefuncHandler({
  route: "/api/telefunc"
});

// We can't use `telefuncRoute` anymore
app.post("/api/telefunc", handler);
```

Those two points non problems if packages leveraging `universal-middleware` are used directly by the user, as one can override the routes manually.

But even for a package such as `vike-telefunc`, either the default route will be applied by default, or non-default if the user overrides them.

So the only issue remaining is the first point. How to represent a universal route, and how to convert such route to adapters compatible ones.

We can create a `@universal-middleware/tools` package that would export helpers like `toHonoRoute(route: string): string`, that can then be used by `vike-telefunc` or alike.

**Comment by magne4000** [comment]
It does work indeed :)

**Comment by brillout** [comment]
Another pro: we can implement it in Vike land including the magic number, so I guess we can close this.

Thanks for the conversation :)
