### ISSUE TITLE
Server hanging upon installing context middleware

### ISSUE THREAD

**Issue by brillout** [magne4000/universal-middleware#74]
Reproduction: https://github.com/brillout/telefunc/blob/416e87e6a8c0da31449ff044fa5a0cbb60659dd2/examples/authentication/server/index.ts#L33

**Comment by magne4000** [comment]
See https://github.com/magne4000/universal-middleware/issues/73#issuecomment-2511512676

**Comment by brillout** [comment]
I wonder if there is a way to throw an error instead of hanging. Maybe it isn't that much of priority though, given that universal-middleware won't be directly used by users.
