### ISSUE TITLE
Access original request object

### ISSUE THREAD

**Issue by brillout** [magne4000/universal-middleware#75]
```js
const contextMiddleware = ((value) => (request, ctx) => {
  return {
    // ctx.req is Express.js's request object
    user: ctx.req.user
    ...ctx,
  };
})
```

For example, if the user wishes to use an Express.js authentication middleware that populates `req.user`.

It will also enable users to access it over `pageContext.req.user`.
 
It seems to be a blocker for many use cases.

**Comment by magne4000** [comment]
There is actually a third undocumented parameter `runtime` for this purpose:

```ts
const contextMiddleware = ((value) => (request, ctx, runtime) => {
  if (runtime.adapter === 'express') {
    const req = runtime.req
    // ...
  }
// ...
})
```

It's currently undocumented because I'm still not sure what the actual user-facing API should look like for it.

**Comment by brillout** [comment]
Neat it also contains `res` :+1:
